name: split_bill
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  uuid: 3.0.6
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  sqflite: ^2.0.3+1
  multiavatar: ^0.1.5
  flutter_svg: ^1.1.5
  indexed: ^0.0.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

